package lib.communication;

public interface DC {
    String SERVER_CONNECTION_ERROR = "SERVER CONNECTION ERROR";
    String GENERAL_ERROR = "GENERAL ERROR";
    String ALREADY_LOGGED_IN = "-ALREADY LOGGED IN";
    String NO_ERROR = "";
    String USER_OFFLINE = "USER OFFLINE";
    String NO_INFO = "noinfo";
    String INCORRECT_PASSWORD = "INCORRECT PASSWORD";

    String LOGIN_USER = "LOGIN USER";
    String CHECK_IF_USERNAME_ALREADY_EXISTS = "CHECK IF USERNAME ALREADY EXISTS";
    String REGISTER_USER = "REGISTER USER";

    String LOGOUT = "LOGOUT";
    String DISCONNECT = "DISCONNECT";

    String FORWARD_MESSAGE = "FORWARD MESSAGE";
    String RECEIVE_MESSAGE = "RECEIVE MESSAGE";
    String USERNAME_DOES_NOT_EXIST = "USERNAME DOES NOT EXIST";
}
